# Generated by Django 3.2.10 on 2022-08-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('math', models.CharField(max_length=30)),
                ('physics', models.CharField(max_length=30)),
                ('history', models.CharField(max_length=30)),
                ('biology', models.CharField(max_length=30)),
                ('geography', models.CharField(max_length=30)),
                ('math_score', models.IntegerField(default=0)),
                ('physics_score', models.IntegerField(default=0)),
                ('history_score', models.IntegerField(default=0)),
                ('biology_score', models.IntegerField(default=0)),
                ('geography_score', models.IntegerField(default=0)),
                ('all_score', models.IntegerField(default=0)),
            ],
        ),
    ]
